#ifndef CONSTANTS_H
#define CONSTANTS_H
const float SCREEN_WIDTH = 1000;
const float SCREEN_HEIGHT = 750;
const float WORK_PANEL = 750;
const float SIDE_BAR = 250;


const int SB_MOUSE_POSITION = 0;
const int SB_MOUSE_CLICKED = SB_MOUSE_POSITION + 1;
const int SB_KEY_PRESSED = SB_MOUSE_CLICKED + 2;

enum TOKEN_TYPES {INTEGER,DOUBLE,FUNCTION,OPERATOR,LPAREN,RPAREN,TOKEN};
#endif // CONSTANTS_H
